<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit86a26f0703a07399597653198daa90a6
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Thedudeguy\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Thedudeguy\\' => 
        array (
            0 => __DIR__ . '/..' . '/thedudeguy/rcon/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit86a26f0703a07399597653198daa90a6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit86a26f0703a07399597653198daa90a6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit86a26f0703a07399597653198daa90a6::$classMap;

        }, null, ClassLoader::class);
    }
}
